### PR TITLE
Fix for newer arduino version

### PR DESCRIPTION
**Pull request by nutcase84**

### CODE REVIEW

**Comment by bgolab** [comment]
I tried arduino 1.6.5:
Arduino: 1.6.5 (Windows 7), Board: "Arduino Uno"

Using library EEPROM in folder: C:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\libraries\EEPROM 

Using library SD in folder: C:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\libraries\SD 

Using library SPI in folder: C:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\libraries\SPI 



C:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IC:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\cores\arduino -IC:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\variants\standard -IC:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\libraries\EEPROM -IC:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\libraries\SD\src -IC:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\libraries\SPI C:\Users\abg015\AppData\Local\Temp\build8011603945389636597.tmp\TinyBasicPlus.cpp -o C:\Users\abg015\AppData\Local\Temp\build8011603945389636597.tmp\TinyBasicPlus.cpp.o 

In file included from C:\Users\abg015\Desktop\news\tiny2\bin\arduino-1.6.5\hardware\arduino\avr\cores\arduino/Arduino.h:28:0,
                 from TinyBasicPlus.ino:81:
TinyBasicPlus.ino:278:33: error: variable 'keywords' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
TinyBasicPlus.ino:370:33: error: variable 'func_tab' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
TinyBasicPlus.ino:385:31: error: variable 'to_tab' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
TinyBasicPlus.ino:390:33: error: variable 'step_tab' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
TinyBasicPlus.ino:395:34: error: variable 'relop_tab' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
TinyBasicPlus.ino:415:36: error: variable 'highlow_tab' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
variable 'keywords' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

**Comment by nutcase84** [comment]
It compiles & runs fine on both my Due and my Uno. I'm on Linux running 1.6.5.

**Comment by bgolab** [comment]
I tried arduino 1.6.5 for Windows. Uno board was selected.

Thanks,Bogdan

**Comment by nutcase84** [comment]
The errors that you are receiving are exactly the same errors as the unmodified version without my commit. Are you sure you are using my commit?

**Comment by bgolab** [comment]
Yes, you are right. I took master copy instead of patched file. It compiles without errors!
I am sorry for not testing the right build.
===
Unfortunately there is very little memory available for variables:
"Global variables use 2,003 bytes (97%) of dynamic memory, leaving 45 bytes for local variables. Maximum is 2,048 bytes. Low memory available, stability problems may occur."

**Comment by nutcase84** [comment]
Low memory doesn't seem to be a problem in my testing. I think it reserves variable space, as it says 999 bytes free on my Uno on startup.

**Pull request merged**
